### ISSUE TITLE
INSERT keyword not highlighting within trigger declaration

### ISSUE THREAD

**Issue by mcandre** [atom/language-sql#78]
Hi, I noticed that the MySQL parser is not highlighting `INSERT` as a SQL keyword when this keyword appears within a trigger declaration.

**Comment by rsese** [comment]
Thanks again for reporting!

In addition to the rest of the template information, as with other issues in language repositories a minimal code snippet to copy/paste would be super helpful for us.

---

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.


Thanks for understanding and meeting us half way :grinning:
