### ISSUE TITLE
IF token mis-highlighted for CREATE TABLE IF NOT EXISTS... statements

### ISSUE THREAD

**Issue by mcandre** [atom/language-sql#79]
`IF` inside of `CREATE TABLE IF NOT EXISTS`... is highlighted incorrectly. It should be the same keyword color as the rest of these tokens, but instead language-sql is highlighting as if `IF` were the table name.

See https://dev.mysql.com/doc/refman/5.7/en/create-table.html

**Comment by rsese** [comment]
Hmm, this is what I see in Atom 1.37.0 on macOS 10.12.6 (I grabbed a full example from [StackOverflow](https://stackoverflow.com/questions/54053043/mysql-create-table-if-not-exists-and-insert-record-only-if-table-was-created)):

![sql-if-not-exists](https://user-images.githubusercontent.com/734194/58072311-e62a7900-7b64-11e9-99d6-7f54003d59e8.png)

Going to close since I can't reproduce but if you have more information or I'm misunderstanding, please let me know.

Filling out the template would have been really helpful here - for example:

* Did you reproduce in safe mode?
* What version of Atom are you running?
* What operating system?
* Do you have a screenshot that shows what you're seeing?
* Do you have a full example we can copy/paste?

I think we've mentioned this before but for future issues, please fill out the issue template - the template provides useful baseline information for us when looking at issues.  Issues without the template filled out may be closed at the discretion of whichever maintainer is triaging your issue.
