### ISSUE TITLE
DELIMITER not highlighting

### ISSUE THREAD

**Issue by mcandre** [atom/language-sql#80]
The MySQL `DELIMITER` keyword is not highlighting.

**Comment by rsese** [comment]
As mentioned in https://github.com/atom/language-sql/issues/79#issuecomment-494254865, if you can fill out the template that would be super helpful and we're happy to take a look.

---

We require the template to be filled out on all new issues and pull requests so if you can open a new issue with the template filled out, that would be helpful for us. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way :grinning:
