### ISSUE TITLE
Lack of validation for missing DELIMITER in triggers

### ISSUE THREAD

**Issue by mcandre** [atom/language-sql#81]
MySQL rejects statements within `TRIGGER` declarations, which typically require semicolons, unless an alternative `DELIMITER` is defined prior to the trigger declaration.

It would be really helpful to highlight `TRIGGER` declarations in SQL code that are missing custom `DELIMITER`s, so that the user catches this mistake in the editor, as opposed to later at runtime. As a bonus, it would also be helpful to point out when SQL code neglects to explicitly reset `DELIMITER ;` following each trigger declaration.

**Comment by rsese** [comment]
Thanks for the suggestion - I chatted with another maintainer about this and wanted to share that for the language packages (especially those without a Tree-sitter grammar), highlighting specific errors isn't something these packages would generally do and not something we would likely add.  For functionality like this, a something like a linter would probably be more appropriate.

Since this isn't something the team would work on, I'm going to go ahead and close this issue but thanks again for the suggestion.
